<template>
  <div class="page" id="page">
  <div id="hostqueue" class="container">
  <div class="queue">
    <h1 class="greeting">Writers Guide</h1>
    <span>Greetings writer!<br>Let's go over the basics to submitting and formatting your Hivezine posts!<br><br>When you're ready to submit a post, you need to copy and paste it into the <a href="https://scratch.mit.edu/studios/33586934/comments" target="_blank">Hivezine studio</a>. How you do this is <b>very important.</b> When commenting your post, the first, main comment needs to be the title of your post. Once you've commented your title, reply to your original comment with your post itself. Your post can be in multiple replies, they'll be put together! And if you ever mess up or notice you made a typo, you can delete your posts! Just click on the title of your post, and you'll see a little delete button. Unless they break Community Guidelines or you have a good reason, please don't delete posts other than your own.<br>You can also pin comments to the homepage when clicking on a post and clicking the pin button. Please only pin posts that are important announcements!<br><br>With formatting, Hivezine posts support <a href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML">HTML</a>. You are <b>not</b> required to use HTML, you can write your posts basically like a Scratch comment. HTML allows you to have greater control, options, and formatting, if you want it. There's lots of useful tags in HTML that you can use in your posts, however, we'll just be focusing on a few that you will most likely be using. If you need help with formatting ever, there's some great guides online, or you can ask <a href="https://scratch.mit.edu/studios/33687618/comments">here</a>.<br><br>
      
      <li class="post"><ul><h1>HTML Reference:</h1><li>&lt;b>&lt;/b> | These are bold tags, they make text <b>bold</b>.</li><li>&lt;u>&lt;/u> | These are underline tags, they make text <u>underlined.</u></li><li>&lt;i>&lt;/i> | These are itallic tags, they make text <i>itallic</i>.</li><li>&lt;br> | This is a break tag, it breaks<br>up<br>text.</li><li>&lt;center>&lt;/center> | These are center tags, they... <center>center elements</center></li><li>&lt;a href="https://scratch.mit.edu/">&lt;/a> | These are anchor, or link tags, they let you <a href="https://scratch.mit.edu/">link</a> to things.</li><li>&lt;img src="https://scratch.mit.edu/images/emoji/meow.png"> | This is an image tag, it makes images <img src="https://scratch.mit.edu/images/emoji/meow.png"></li></ul></li>
    
    <li class="post"><ul><h1>Emoji Reference:</h1><li>:happy: - 😊</li><li>:sad: - ☹️</li><li>:cool: - 😎</li><li>:hmm: - 🤔</li><li>:crylaugh: - 😂</li><li>:thumbsup: - 👍</li><li>:heart: - ❤️</li><li>:pride: - 🏳️‍🌈</li><li>:trans: - 🏳️‍⚧️</li><li>:nails: - 💅</li><li>:skull: - 💀</li><li>:sparkle: - ✨</li><li>:yay: - 🎉</li><li>:leaves: - 🍂</li><li>:pumpkin: - 🎃</li><li>:boo!: - 👻</li><li>:bat: - 🦇</li><li>:eye::lip::eye: - 👁👄👁</li><li>:shrug: - ¯\_(ツ)_/¯</li><li>:pablo: - (͠≖ ͜ʖ͠≖)</li><sub>psst...there's a secret one too, can you figure it out..?</sub></ul></li>
    </span>
  </div>
  </div>
  </div>
</template>