<template>
  <div class="page">
    <div class="container">
      <div id="text" class="queue">
        <h1 class="greeting">The Gaehive Website</h1>
        <h3>Welome to the official Gaehive website! This website was built by <a href="https://scratch.mit.edu/users/LegoManiac04/">LegoManiac04</a> for the Scratch Studio known as the Gaehive. Here, you can find useful links, as well as some useful and fun tools, like the Hivezine and the host queue!</h3>
        <span><i>To follow Scratch Community Guidelines, all "user-generated" content on this site is fetched and stored from Scratch comments. Users cannot generate any content on this website.<br>For more information, please check out <router-link to="/docs/how-we-follow-guidelines">this page</router-link>.</i></span>

        <div v-if="loading && !error" class="loader"></div>
        
        <div class="posts">
          <div class="post" v-for="(item, index) in this.posts">
            <div class="title">
              <div class="pinnedPost">
                <div class="material-symbols-rounded">push_pin</div>
                <router-link :to="'/hivezine/post/' + item.id">{{ item.title }}</router-link>
              </div>
              <div class='username'>
                <span>
                  <a :href="'https://scratch.mit.edu/users/' + item.user ">{{ item.user }}</a> on {{ item.date }}
                </span>
                <img :src="'https://uploads.scratch.mit.edu/get_image/user/' + item.uid + '_500x500.png'">
              </div>
            </div>
            <div class='content' v-html=item.post></div>
          </div>
        </div>
    
        <div class="credits">
          <span>This website is an <a href="https://github.com/PurpleZen/gaehive">open source project</a> using API data from <a href="https://scratch.mit.edu/">Scratch</a> by the Scratch Foundation and authentication API by <a href="https://auth.itinerary.eu.org/">Looky1173</a>.<br>Content generated by Scratch users is used under the <a href="https://creativecommons.org/licenses/by-sa/2.0/">Creative Commons Attribution-ShareAlike 2.0 license</a>.</span>
        </div>
        
      </div>
    </div>
  </div>
</template>

<script>
  import symbcode from "@/data/symbcode.json"
  import symbols from "@/data/symbols.json"
  
  export default {
    data() {
      return {
        loading: null,
        error: null,
        title: null,
        posts: null,
        data: null,
        symbcode: null      
      }
    },
    
    async mounted() {
      this.loading = true

      if (!localStorage["pin"]) {
        this.noPostData()
      } else {
      this.getPostData()
      }
      
    },
    methods: {
      async noPostData() {
        const postdata = await fetch('https://gaehivecloset.fizzyizzy.repl.co/hivezine/pin')
        const post = await postdata.json()
        localStorage.setItem('pin', JSON.stringify(post))

        this.getPostData()
      },
      
      async getPostData() {
        this.symbcode = (symbcode)
        this.symbols = (symbols)
        
        this.data = JSON.parse(localStorage["pin"])
        this.symbcode.forEach(string => {
      var is = this.symbcode.indexOf(string)
      for ( var i = 0; i < this.data.length; i++){
        let regex = new RegExp(string, "g")
        this.data[i].title = this.data[i].title.replace(regex, this.symbols[is]);
        this.data[i].post = this.data[i].post.replace(regex, this.symbols[is]);
        }
      })
      this.posts = this.data
      this.loading = false
        this.refresh()
      },

      async refresh() {
        const postdata = await fetch('https://gaehivecloset.fizzyizzy.repl.co/hivezine/pin')
        const post = await postdata.json()
        localStorage.setItem('pin', JSON.stringify(post))

        this.data = JSON.parse(localStorage["pin"])
        this.symbcode.forEach(string => {
      var is = this.symbcode.indexOf(string)
      for ( var i = 0; i < this.data.length; i++){
        let regex = new RegExp(string, "g")
        this.data[i].title = this.data[i].title.replace(regex, this.symbols[is]);
        this.data[i].post = this.data[i].post.replace(regex, this.symbols[is]);
        }
      })
        this.posts = this.data
      }
    }
  }
</script>
