<template>
  <div class="page">
  <div class="container">
  <div id="text" class="queue">
    <h1 class="greeting">The Gaehive Website</h1>
    <h3>Welome to the official Gaehive website! This website was built by <a href="https://scratch.mit.edu/users/LegoManiac04/">LegoManiac04</a> for the Scratch Studio known as the Gaehive. Here, you can find useful links, as well as some useful and fun tools, like the host queue, and our news bulletin!</h3>
    <div class="credits">
      <span>This website is an <a href="https://github.com/PurpleZen/gaehive">open source project</a> using API data from <a href="https://scratch.mit.edu/">Scratch</a> by the Scratch Foundation and authentication API by <a href="https://auth.itinerary.eu.org/">Looky1173</a>.<br>Content generated by Scratch users is used under the <a href="https://creativecommons.org/licenses/by-sa/2.0/">Creative Commons Attribution-ShareAlike 2.0 license</a>.</span>
    </div>
  </div>
  </div>

  </div>
</template>

<script>
  export default {
    data() {
      return {
        loaded: null
      }
    },
    mounted() {

      this.loaded = true
      
    }
  }
</script>