<template>
  <div class="centerpage">
        <h1 class="greeting">The Gaehive Website</h1>
    
        <h3>Built for the Gaehive, a Scratch Studio and community supporting LGBTQ+ individuals.<br>This website is home to the Hivezine and useful tools and resources.</h3>

    <h3><a class="button" href="https://scratch.mit.edu/users/LegoManiac04/" target="_blank">Made with &lt;3 by LegoManiac04</a></h3>
    
        <div class="credits">
          <span>This website is an <a href="https://github.com/PurpleZen/gaehive" target="_blank">open source project</a> using API data from <a href="https://scratch.mit.edu/" target="_blank">Scratch</a> by the Scratch Foundation and authentication API by <a href="https://auth.itinerary.eu.org/" target="_blank">Looky1173</a>.<br>Content generated by Scratch users is used under the <a href="https://creativecommons.org/licenses/by-sa/2.0/" target="_blank">Creative Commons Attribution-ShareAlike 2.0 license</a>.</span>
        </div>
        <h5><i><router-link to="/docs/us-and-scratch-guidelines">Learn how this website follows Scratch Community Guidelines</router-link>.</i></h5>
    Powered by 
    <div>
      <a href="https://vuejs.org/" target="_blank"><img class="poweredby" src="https://skillicons.dev/icons?i=vue"></a>
      <a href="https://vercel.com/" target="_blank"><img class="poweredby" src="https://skillicons.dev/icons?i=vercel"></a>
      <a href="https://supabase.com/" target="_blank"><img class="poweredby" src="https://skillicons.dev/icons?i=supabase"></a>
    </div>
  </div>
</template>

<script>
  import { useMeta } from 'vue-meta'
  export default {
    created() {
      useMeta({
        title: 'Gaehive • Welcome!'
      });
    }
  }
</script>

<style scoped>
.centerpage {
  display: grid;
  align-content: center;
  height: calc(100vh - 50px);
  justify-items: center;
  width: 100%;
}
</style>